resourcePath = "./resource"
dbName = "zoobc.db"
badgerDbName="zoobc_1_kv/"
nodeKeyFile = "node_keys.json"
snapshotPath = "./resource/snapshots"

# Peer
peerPort=8001
myAddress="127.0.0.1"
wellknownPeers=["n1.alpha.proofofparticipation.network:8001","n2.alpha.proofofparticipation.network:8001","n3.alpha.proofofparticipation.network:8001"]

apiRPCPort=7000
apiHTTPPort=7001
maxAPIRequestPerSecond=10
# comment out or set to 0 to disable http proxy, only enable in dev mode
monitoringPort=9090
cpuProfilingPort=6060
apiReqTimeoutSec=2


ownerAccountAddress = "ZBC_AQTEIGHG_65MNY534_GOKX7VSS_4BEO6OEL_75I6LOCN_KBICP7VN_DSUWBLM7"

smithing=true
proofOfOwnershipReqTimeoutSec = 2
# Log Levels
# Available log level: info, warn, error, fatal, panic
logLevels=["fatal", "error", "panic"]

# to show all log on terminal/cli that recoreded in .log/log_files
logOnCli= false
# to show usefull information on terminal/cli. The logOnCli must be false
cliMonitoring=true

walletCertFileName= "wallet.zbc"

#apiCertFile="./resource/network.crt"
#apiKeyFile="./resource/network.key"