apiHTTPPort = 7001
apiReqTimeoutSec = 2
apiRPCPort = 7000
# to show usefull information on terminal/cli. The logOnCli must be false
cliMonitoring = true
cpuProfilingPort = 6060
dbName = "zoobc.db"
# Available log level: info, warn, error, fatal, panic
logLevels = ["fatal","error","panic"]
# to show all log on terminal/cli that recoreded in .log/log_files
logOnCli = false
maxAPIRequestPerSecond = 10
monitoringPort = 9090
myAddress = "127.0.0.1"
nodeKeyFile = "node_keys.json"
ownerAccountAddress = "000000002f714c0ee3b1469902bd56f1fd444c32e0fdeae880eb7718c34fc4694a4aed55"
peerPort = 8001
proofOfOwnershipReqTimeoutSec = 2
resourcePath = "resource"
smithing = true
snapshotPath = "resource/snapshots"
walletCertFileName = "wallet.zbc"
wellknownPeers = ["127.0.0.1:8002"]

#apiCertFile="./resource/network.crt"
#apiKeyFile="./resource/network.key"
