antispamcpulimitpercentage = 75
antispamfilter = true
antispamp2prequestlimit = 150
apihttpport = 7001
apireqtimeoutsec = 2
apirpcport = 7000
climonitoring = true
cpuprofilingport = 6060
dbname = "zoobc.db"
loglevels = ["fatal","error","panic"]
logoncli = false
maxapirequestpersecond = 10
monitoringport = 9090
myaddress = "127.0.0.1"
nodekeyfile = "node_keys.json"
owneraccountaddress = "000000002f714c0ee3b1469902bd56f1fd444c32e0fdeae880eb7718c34fc4694a4aed55"
peerport = 8001
proofofownershipreqtimeoutsec = 2
resourcepath = "/Users/ali/go/src/github.com/zoobc/zoobc-core/resource"
smithing = true
snapshotpath = "/Users/ali/go/src/github.com/zoobc/zoobc-core/resource/snapshots"
walletcertfilename = "wallet.zbc"
wellknownpeers = ["127.0.0.1:8002"]
