resourcePath = "./resource"
dbName = "zoobc_2.db"
badgerDbName="zoobc_2_kv/"
nodeKeyFile = "node_keys_2.json"
snapshotPath = "./resource/snapshots_2"

# Peer
peerPort=8002
myAddress="127.0.0.1"
wellknownPeers=["127.0.0.1:8001"]

apiRPCPort=3002
maxAPIRequestPerSecond=10
# comment out or set to 0 to disable http proxy, only enable in dev mode
monitoringPort=9092
cpuProfilingPort=6062
apiReqTimeoutSec=2

ownerAccountAddress = "ZBC_HJYRRTEP_QQYV5FCN_7IKBGOSQ_KI4RFFT2_QHZW7EWJ_CN56HL3F_EU2SGEHU"

smithing=true
proofOfOwnershipReqTimeoutSec = 1
# Log Levels
# Available log level: info, warn, error, fatal, panic
logLevels=["debug", "warn", "info", "fatal", "error", "panic"]

# to show all log on terminal/cli that recoreded in .log/log_files
logOnCli= false
# to show usefull information on terminal/cli. The logOnCli must be false
cliMonitoring=true

#apiCertFile="./resource/network.crt"
#apiKeyFile="./resource/network.key"