dbPath = "./resource/"
dbName = "zoobc_2.db"
configPath = "./resource/"
nodeKeyFile = "node_keys.json"

# Peer
peerPort=8002
myAddress="127.0.0.1"
wellknownPeers=["127.0.0.1:8001"]

apiRPCPort=3002
apiHTTPPort=3032
# nodeSecretPhrase = "demanding unlined hazard neuter condone anime asleep ascent capitol sitter marathon armband"
ownerAccountAddress = "BCZnSfqpP5tqFQlMTYkDeBVFWnbyVK7vLr5ORFpTjgtN"

proofOfOwnershipReqTimeoutSec = 1