dbPath = "./resource/"
dbName = "zoobc_2.db"
badgerDbPath="./resource"
badgerDbName="zoobc_2_kv/"
configPath = "./resource/"
nodeKeyFile = "node_keys_2.json"
snapshotPath = "./resource/snapshots_2"

# Peer
peerPort=8002
myAddress="127.0.0.1"
wellknownPeers=["127.0.0.1:8001"]

apiRPCPort=3002
apiHTTPPort=3032
monitoringPort=9092
cpuProfilingPort=6062
apiReqTimeoutSec=2

ownerAccountAddress = "ZBC_HJYRRTEP_QQYV5FCN_7IKBGOSQ_KI4RFFT2_QHZW7EWJ_CN56HL3F_EU2SGEHU"

smithing=true
proofOfOwnershipReqTimeoutSec = 1
# Log Levels
# Available log level: info, warn, error, fatal, panic
logLevels=["fatal", "error", "panic", "warn"]

apiCertFile="./resource/network.crt"
apiKeyFile="./resource/network.key"