dbPath = "./resource/"
dbName = "zoobc_4.db"
configPath = "./resource/"
nodeKeyFile = "node_keys.json"


# Peer
peerPort=8004
myAddress="127.0.0.1"
wellknownPeers=["127.0.0.1:8002"]

apiRPCPort=3004
apiHTTPPort=3034
# nodeSecretPhrase = "spree uplifted stapling quotable disfigure lair deduct untying timothy maggot cryptic unrigged"
ownerAccountAddress = "BCZD_VxfO2S9aziIL3cn_cXW7uPDVPOrnXuP98GEAUC7"

proofOfOwnershipReqTimeoutSec = 1
# Log Levels
logLevels=["warn", "fatal", "error", "panic"]