dbPath = "./resource/"
dbName = "zoobc_3.db"
badgerDbPath="./resource"
badgerDbName="zoobc_3_kv/"
configPath = "./resource/"
nodeKeyFile = "node_keys_3.json"

# Peer
peerPort=8003
myAddress="127.0.0.1"
wellknownPeers=["127.0.0.1:8002"]
Version = "0.1.31"
CodeName = "ZooBC-Alpha"

apiRPCPort=3003
apiHTTPPort=3033
monitoringPort=9093
apiReqTimeoutSec=2

ownerAccountAddress = "BCZKLvgUYZ1KKx-jtF9KoJskjVPvB9jpIjfzzI6zDW0J"

proofOfOwnershipReqTimeoutSec = 1
# Log Levels
# Available log level: info, warn, error, fatal, panic
logLevels=["fatal", "error", "panic"]
