dbPath = "./resource/"
dbName = "zoobc_4.db"
badgerDbPath="./resource"
badgerDbName="zoobc_4_kv/"
configPath = "./resource/"
nodeKeyFile = "node_keys_4.json"
snapshotPath = "./resource/snapshots"

# Peer
peerPort=8004
myAddress="127.0.0.1"
wellknownPeers=["127.0.0.1:8001"]
Version = "0.0.31"
CodeName = "ZooBC-Alpha"

apiRPCPort=3004
apiHTTPPort=3034
monitoringPort=9094
apiReqTimeoutSec=2

ownerAccountAddress = "nK_ouxdDDwuJiogiDAi_zs1LqeN7f5ZsXbFtXGqGc0Pd"

# smithing=true
proofOfOwnershipReqTimeoutSec = 1
# Log Levels
# Available log level: info, warn, error, fatal, panic
logLevels=["fatal", "error", "panic"]
