dbPath = "./resource/"
dbName = "zoobc_3.db"
configPath = "./resource/"
nodeKeyFile = "node_keys_3.json"

# Peer
peerPort=8003
myAddress="127.0.0.1"
wellknownPeers=["127.0.0.1:8002"]

apiRPCPort=3003
apiHTTPPort=3033
apiReqTimeoutSec=2

ownerAccountAddress = "BCZKLvgUYZ1KKx-jtF9KoJskjVPvB9jpIjfzzI6zDW0J"

proofOfOwnershipReqTimeoutSec = 1
# Log Levels
logLevels=["warn", "fatal", "error", "panic"]